### ISSUE TITLE
Capacity tariff Flanders (Belgium) - Extra data-objects, telegram change

### ISSUE THREAD

**Issue by Giolovin** [DCSBL/python-homewizard-energy#150]
Would it be possible to add the following data objects that are published on the DSMR P1 port with KW as measurement to the HomeWizard integration? These measurements are very important for Flemish users for the new capacity tariff which the distribution system operator will highly likely introduce on the 1st of January 2023. 

The changes that have been made to eMUCs for the introduction of the capacity tariff in Flanders are highlighted in yellow in this pdf delivered by the the distribution system operator (Fluvius):
[https://maakjemeterslim.be/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhlblJ4YW14cU5XdHRhalZsWkRWbmJIaDNNak4zYmpReGFUazRkd1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpVjJsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW1VdFRWVkRVMTlRTVY5RlpGOHhYemRmTVM1d1pHWWlPeUJtYVd4bGJtRnRaU285VlZSR0xUZ25KMlV0VFZWRFUxOVFNVjlGWkY4eFh6ZGZNUzV3WkdZR093WlVPaEZqYjI1MFpXNTBYM1I1Y0dWSkloUmhjSEJzYVdOaGRHbHZiaTl3WkdZR093WlUiLCJleHAiOiIyMDIyLTEyLTEyVDExOjQ1OjMwLjg0NVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--1c68e8d843e99a6f94dc825253327341be27fe84/e-MUCS_P1_Ed_1_7_1.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22e-MUCS_P1_Ed_1_7_1.pdf%22%3B+filename%2A%3DUTF-8%27%27e-MUCS_P1_Ed_1_7_1.pdf](url)

Example
```
/FLU5\253769484_A

0-0:96.1.4(50217)
0-0:96.1.1(3153414733313030313731323436)
0-0:1.0.0(221212123022W)
1-0:1.8.1(003180.623*kWh)
1-0:1.8.2(004438.105*kWh)
1-0:2.8.1(004994.116*kWh)
1-0:2.8.2(001924.378*kWh)
0-0:96.14.0(0001)
1-0:1.4.0(00.008*kW)
1-0:1.6.0(221205163000W)(03.686*kW)
0-0:98.1.0(0)(1-0:1.6.0)(1-0:1.6.0)()
1-0:1.7.0(00.655*kW)
1-0:2.7.0(00.000*kW)
1-0:21.7.0(00.000*kW)
1-0:41.7.0(00.000*kW)
1-0:61.7.0(00.714*kW)
1-0:22.7.0(00.059*kW)
1-0:42.7.0(00.000*kW)
1-0:62.7.0(00.000*kW)
1-0:32.7.0(230.8*V)
1-0:52.7.0(000.0*V)
1-0:72.7.0(231.3*V)
1-0:31.7.0(005.70*A)
1-0:51.7.0(004.51*A)
1-0:71.7.0(007.48*A)
0-0:96.3.10(1)
0-0:17.0.0(999.9*kW)
1-0:31.4.0(999*A)
0-0:96.13.0()
!FB50
```

These are the most important:

**Current average demand -
Active energy import
1-0:1.4.0*255**

Maximum demand – Active
energy import of the running
month
1-0:1.6.0*255

Maximum demand – Active
energy import of the last 13
months
0-0:98.1.0*255
(1-0:1.6.0*255 ,2)
(1-0:1.6.0*255, 5)
Last 13 months of the maximum demand register (Time of
appearance & Value)

I would be very thankful if you could manage to incorporate these changes, because this would mean these measurements would become easily accessible in Home Assistant.

[e-MUCS_P1_Ed_1_7_1.pdf](https://github.com/DCSBL/python-homewizard-energy/files/10207790/e-MUCS_P1_Ed_1_7_1.pdf)

**Comment by DCSBL** [comment]
Hey, thank you for your feature request.

I would love it to add this, but these values are not exposed by the API. I do not prefer adding telegram parsing to this library because this can give some legacy issues later on. HomeWizard currently works on adding more datapoints but I can't give an exact timeline.

I think a nice in-between is something like this to `configuration.yaml` (from https://community.home-assistant.io/t/homewizard-energy-wi-fi-p1-meter-kwh-meter-energy-socket-and-water-meter/227441/431):

```yaml
rest:
  - authentication: basic
    scan_interval: 10 # Lower has more resolution, but voltage is a bit 'noisy' so it fills your database fast. Be careful.
    resource: http://<ip_address>/api/v1/telegram
    sensor:
      - name: "Current maximum demand"
        device_class: power
        unique_id: <something_random_or_serial_id>_active_maximum_demand # It does not matter what is added here, but it has to be unique.
        state_class: measurement
        unit_of_measurement: W
        value_template: "{{ (value|regex_findall_index('1\\-0\\:1\\.4\\.0\\([0-9.]*')).split('(',1)[-1].strip() | float }}"
      - name: "Maximum demand this month"
        device_class: power
        unique_id: <something_random_or_serial_id>_current_maximum_demand # It does not matter what is added here, but it has to be unique.
        state_class: measurement
        unit_of_measurement: W
        value_template: "{{ (value|regex_findall_index('1\\-0\\:1\\.6\\.0\\([0-9.]*')).split('(',1)[-1].strip() | float }}"
```

I do not have a smart meter with these values, can you see if this works?
